---
- name: "{{ my_name }} - templates"
  ansible.builtin.template:
    src: "templates/{{ my_file }}/{{ tmpl.sub + '/' if tmpl.sub is defined else '' }}{{ tmpl.name }}.j2"
    dest: "{{ tmpl.dest }}/{{ tmpl.name }}"
    owner: "{{ tmpl.owner|default('root') }}"
    group: "{{ tmpl.group|default('root') }}"
    mode: "{{ tmpl.mode|default('0644') }}"
    force: "{{ tmpl.force|default('yes') }}"
  loop: "{{ templates }}"
  loop_control:
    loop_var: "tmpl"
