---
- name: "{{ my_name }} - build layout nolink list (set fact) (dir)"
  ansible.builtin.set_fact:
    path_list_ll: "{{ path_list_ll|default([]) + [ 'mkdir -p ' + retronas_path + '/' + system_key + '/' + item[system_key] + ';' ] }}"
  loop: "{{ system_map }}"
  when: top_level_paths is not defined and
    item[system_key] is defined and
    item[system_key] | length > 0

- name: "{{ my_name }} - build layout nolink list (set fact) (top level paths) (dir)"
  ansible.builtin.set_fact:
    path_list_tl: "{{ path_list_tl|default([]) + [ 'mkdir -p ' + retronas_path + '/' + system_key + '/' + item.1.name + '/' + item.0[system_key] + ';' ] }}"
  loop: "{{ system_map|product(top_level_paths)|list }}"
  when: top_level_paths is defined and
    item.1.enabled is true and
    item.0[system_key] is defined and
    item.0[system_key] | length > 0 and
    item.1.systems is true
