---
my_name: "Generic Extra dir(s)"
my_file: "install_romdir"
module_name: "extradirs"

top_level_paths:
  - { name: "bios",       generic: "bios",        enabled: yes, systems: yes }
  - { name: "saves",      generic: "saves",       enabled: yes, systems: yes }
  - { name: "savestates", generic: "savestates",  enabled: yes, systems: yes }
  - { name: "wallpapers", generic: "wallpapers",  enabled: yes, systems: no }
