- name: "{{ my_name }} - Load RetroNAS config"
  ansible.builtin.include_vars: retronas_vars.yml

- ansible.builtin.import_role:
    name: retronas.role.package.latest

- name: "{{ my_name }} - clean up old installs"
  ansible.builtin.file:
    path: "{{ srcdir }}"
    force: yes
    state: absent

- name: "{{ my_name }} - create build dirs"
  ansible.builtin.file:
    path: "{{ srcdir }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: "{{ my_name }} - Download SDK installer"
  ansible.builtin.get_url:
    url: https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh
    dest: "{{ srcdir }}"
    owner: root
    group: root
    mode: 0755

- name: "{{ my_name }} - Install DotNet SDK"
  ansible.builtin.shell:
    cmd: "./dotnet-install.sh --version {{ version }} 2>&1 | tee {{ retronas_root }}/log/{{ my_file }}.log"
    chdir: "{{ srcdir }}"
    executable: /bin/bash
  environment:
    DOTNET_ROOT: "{{ retronas_root }}/bin/dotnetcore6"
    DOTNET_INSTALL_DIR: "{{ retronas_root }}/bin/dotnetcore6"
    TMPDIR: "{{ srcdir }}"