---
- name: "{{ my_name }} - Include systems map"
  ansible.builtin.include_vars: "retronas_systems.yml"
  when: system_map_min is not defined

- name: "{{ my_name }} - Load RetroNAS config"
  ansible.builtin.include_vars: retronas_vars.yml

- name: "{{ my_name }} - create our base"
  ansible.builtin.shell:
    cmd: |
      mkdir -p {{ retronas_path }}
      chown {{ retronas_user }}:{{ retronas_group }} {{ retronas_path }}
      chmod 2755 {{ retronas_path }}
  become: true
  changed_when: false

# retronas generic top level dirs
- ansible.builtin.file:
    path: "{{ retronas_path }}/{{ tlpi.name }}"
    owner: "{{ retronas_user }}"
    group: "{{ retronas_group }}"
    state: directory
    mode: '2755'
  become: true
  loop: "{{ top_level_paths }}"
  loop_control:
    loop_var: tlpi
  when:
    - tlpi.enabled is true

# top level dirs that require systems
- ansible.builtin.set_fact:
    tlp: "{{ tlp|default([]) + [ tlpi.name ] }}"
  loop: "{{ top_level_paths }}"
  loop_control:
    loop_var: tlpi
  when:
    - tlpi.enabled is true
    - tlpi.systems is true

- set_fact:
    tlpsa: "{{ '{' + tlp | join(',') + '}' }}"
  when: tlp | length > 1

- set_fact:
    tlpsa: "{{ tlp.0 }}"
  when: tlp | length == 1

- block:
  - name: "{{ my_name }} - build min processing list (system_key)"
    ansible.builtin.set_fact:
      system_map_min: "{{ system_map | map(attribute='src') | zip( system_map | map(attribute=system_key) ) }}"
  when: system_key is defined

- block:
  - name: "{{ my_name }} - build min processing list"
    ansible.builtin.set_fact:
      system_map_min: "{{ system_map | map(attribute='src')|list }}"
  when: system_key is not defined

- name: "{{ my_name }} - build layout list (set fact)"
  ansible.builtin.set_fact:
    path_list: "{{ path_list|default([]) + [ retronas_path + '/' + tlpsa + '/' + pl.0 ] }}"
  loop: "{{ system_map_min }}"
  loop_control:
    loop_var: pl
    label: "{{ pl.0 }}"

- name: "{{ my_name }} - build layout"
  ansible.builtin.shell:
    cmd: bash -c "mkdir -p {{ path_list|flatten|join(' ') }}"
  become: true
  become_user: "{{ retronas_user }}"
  become_method: sudo
  when: path_list is defined
  changed_when: false

- name: "{{ my_name }} - build systems directory layout (links) (set fact)"
  ansible.builtin.set_fact:
    link_list: "{{ link_list|default([]) + [ 'ln -sfT ' + retronas_path  + '/' + ll.1  + '/' + ll.0.src + ' ' + retronas_path  + '/' + ll.1 + '/' + ll.0.dest + ';' ] }}"
  loop: "{{ system_links|product(tlp) }}"
  loop_control:
    loop_var: ll
    label: "{{ ll.0.src }}"

- name: "{{ my_name }} - build systems directory layout (links)"
  ansible.builtin.shell:
    cmd: bash -c "{{ link_list|join('') }}"
  when: link_list is defined
  changed_when: false

# src, system_key map
- block:
  - name: "{{ my_name }} - build min processing list (system_key)"
    ansible.builtin.set_fact:
      system_map_min: "{{ system_map | map(attribute='src') | zip( system_map | map(attribute=system_key) ) }}"

  - name: "{{ my_name }} - build top level"
    ansible.builtin.file:
      path: "{{ retronas_path }}/{{ system_key }}"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_group }}"
      state: directory
      mode: "0775"

  - name: "{{ my_name }} - build top level share paths"
    ansible.builtin.file:
      path: "{{ retronas_path }}/{{ system_key }}/{{ item.name }}"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_group }}"
      state: directory
      mode: "0775"
    loop: "{{ top_level_paths }}"
    when:
      - top_level_paths is defined
      - item.enabled is true

  - name: "{{ my_name }} - setup directories with symlinks"
    include_tasks: link.yml
    when: nolink is not defined or nolink is false

  - name: "{{ my_name }} - setup directories without symlinks"
    include_tasks: nolink.yml
    when: nolink is defined and nolink is true

  - name: "{{ my_name }} - build systems directory layout (systems)"
    ansible.builtin.shell:
      cmd: "{{ path_list_ll|join('') }}"
    when: path_list_ll is defined
    changed_when: false

  - name: "{{ my_name }} - build systems directory layout (systems) (top_level)"
    ansible.builtin.shell:
      cmd: "{{ path_list_tl|join('') }}"
    when: path_list_tl is defined
    changed_when: false

  when: system_key is defined

#- name: "{{ my_name }} - add top level directory info"
#  ansible.builtin.copy:
#    dest: "{{ item.stat.path }}/dir.txt"
#    content: |
#      this folder structure is the responsiblity of the user to populate
#    owner: "{{ retronas_user }}"
#    group: "{{ retronas_group }}"
#    mode: "0644"
#  loop: "{{ tl_paths.results }}"
#  when: tl_paths is defined and
#        item.stat.exists is true
