my_name: "Samba"
my_file: ""  # required to clear out any play set var

packages:
  - avahi-daemon
  - samba
  - samba-vfs-modules

my_services:
  - avahi-daemon
  - smbd
  - nmbd

config_opts:
  - { section: "global",    option: "min protocol",               value: "CORE"}
  - { section: "global",    option: "netbios name",               value: "retrosmb"}
  - { section: "global",    option: "lanman auth",                value: "yes"}
  - { section: "global",    option: "client lanman auth",         value: "yes"}
  - { section: "global",    option: "ntlm auth",                  value: "yes"}
  - { section: "global",    option: "client ntlm auth",           value: "yes"}
  - { section: "global",    option: "ntlmv2 auth",                value: "yes"}
  - { section: "global",    option: "client ntlmv2 auth",         value: "yes"}
  - { section: "global",    option: "unix extensions",            value: "no"}
  - { section: "global",    option: "allow insecure wide links",  value: "yes"}
  - { section: "global",    option: "socket options",             value: "TCP_NODELAY IPTOS_LOWDELAY SO_KEEPALIVE"}
  - { section: "global",    option: "strict locking",             value: "no"}
  - { section: "global",    option: "strict sync",                value: "no"}
  - { section: "global",    option: "sync always",                value: "no"}
  - { section: "global",    option: "deadtime",                   value: "1560"}
  - { section: "retronas",  option: "include",                    value: "/etc/samba/retronas.conf"}

templates:
  - { name: "retronas.conf", dest: "/etc/samba" }

firewalld_rules:
  - { zone: "retro",  service: "samba" }
  - { zone: "modern", service: "samba-modern" }

changed: false