---
- hosts: localhost

  vars:
    my_name: "nbd-client"
    my_file: "install_nbd-client"
    module_name: "nbd-client"

    packages:
      - nbd-client

    templates:
      - { name: "nbd.conf", dest: "/etc/modules-load.d/" }

  tasks:

    - name: "{{ my_name }} - Load RetroNAS config"
      ansible.builtin.include_vars: retronas_vars.yml

    - ansible.builtin.include_role:
        name: "{{ iroles }}"
      loop:
        - retronas.role.package.latest
        - retronas.role.templates
      loop_control:
        loop_var: "iroles"

    - name: "{{ my_name }} - enable ndb kernel module"
      ansible.builtin.shell:
        cmd: "modprobe nbd"

    - ansible.builtin.import_role:
        name: retronas.role.system-config
