---
# Dependencies
- ansible.builtin.import_playbook: install_romdir.yml

- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "xbox"
    - my_file: "install_xbox"
    - module_name: "xbox"
    - system_key: "xbox"

    - paths:
      - { name: "xbox", dest: "{{ retronas_path }}", owner: "{{ retronas_user }}", group: "{{ retronas_group }}" }

    - templates:
      - { name: "retronas_xbox.conf", dest: "/etc/samba/"  }

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    ansible.builtin.include_vars: retronas_vars.yml

  - ansible.builtin.import_role:
      name: retronas.role.samba

  - ansible.builtin.import_role:
      name: retronas.role.templates

  - name: "{{ my_name }} - symlinks"
    ansible.builtin.file:
      src: "{{ item.src }}"
      dest: "{{ retronas_path }}/xbox/{{ item.dest }}"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_group }}"
      state: link
    with_items:
      - { src: "../roms/microsoft/xbox/games", dest: "games" }
      - { src: "../roms/microsoft/xbox/iso", dest: "iso" }

  - name: "{{ my_name }} - configure includes file"
    ansible.builtin.ini_file:
      path: /etc/samba/smb.conf
      section: xbox
      option: "include"
      value: "/etc/samba/retronas_xbox.conf"

  - ansible.builtin.import_role:
      name: retronas.role.system-config
