- hosts: localhost
  gather_facts: no

  vars:
    module_name: "cockpit-packages"
    module_state: "present"

  roles:
    - retronas.role.filesystems
    - retronas.role.cockpit
    - retronas.role.system-config