---
- hosts: localhost
  gather_facts: false

  vars:
    my_name: "adtpro"
    my_file: "install_{{ my_name }}"
    my_dir: /opt/adtpro
    module_name: "adtpro"

    packages:
      - default-jre

    templates:
      - { name: "{{ my_file }}.sh", dest: "{{ retronas_root }}/scripts", mode: "0755" }
      - { name: "ADTPro.properties", dest: "{{ my_dir }}", force: no }
      - { name: "adtpro_retronas.sh", dest: "{{ my_dir }}",  mode: "0755" }

    paths:
      - { name: "{{ my_name }}", dest: "/opt",                state: "directory", mode: "0755"}
      # - { name: "{{ my_name }}", dest: "{{ retronas_path }}", state: "directory", mode: "0755"}

    config:
      - { filename: "/etc/X11/fluxbox/retronas-menu", option: "[exec] (ADTPro) { /opt/adtpro/adtpro_retronas.sh }", value: "", before: "[end]" }

  tasks:

    - name: "{{ my_name }} - Include systems map"
      ansible.builtin.include_vars: "retronas_systems.yml"

    - name: "{{ my_name }} - Load RetroNAS config"
      ansible.builtin.include_vars: retronas_vars.yml

    - ansible.builtin.include_role:
        name: "{{ iroles }}"
      loop:
        - retronas.role.romdir
        - retronas.role.package.latest
        - retronas.role.paths
        - retronas.role.templates
        - retronas.role.desktop
      loop_control:
        loop_var: "iroles"

    - name: "{{ my_name }} - disks symlink"
      ansible.builtin.file:
        src: "roms/apple/appleii"
        dest: "{{ retronas_path }}/{{ my_name }}"
        state: "link"

    - name: "{{ my_name }} - Install"
      ansible.builtin.shell: "{{ retronas_root }}/scripts/{{ my_file }}.sh 2>&1 | tee {{ retronas_root }}/log/{{ my_file }}.log"
      args:
        creates: "{{ retronas_root}} {{ my_dir }}/adtpro.sh"

    - name: "{{ my_name }} - desktop entry"
      ansible.builtin.lineinfile:
        path: "{{ item.filename }}"
        regexp: "^{{ item.option }}.*"
        line: "{{ item.option }} {{ item.value | default(omit) }}"
        insertbefore: "[end]"
        state: "{{ item.state | default('present') }}"
      loop: "{{ config }}"

    - ansible.builtin.import_role:
        name: retronas.role.system-config
