---
- hosts: localhost
  gather_facts: false

  vars:
    my_name: "RomM CIFS"
    my_file: "install_romm_cifs"
    module_name: "romm_cifs"
    system_key: "romm"
    script_url: 'https://raw.githubusercontent.com/minorOffense/romdirflattener/refs/heads/main/flatten-romdir.sh'
    script_dest: "{{ retronas_root }}/bin/flatten-romdir.sh"
    fattenerscript: "retronas-romm-dirs"

    top_level_paths:
      - { name: "roms",   enabled: yes,  generic: "roms",   systems: yes }

    templates:
      - { name: "retronas-romm-dirs.service", dest: "/etc/systemd/system" }
      - { name: "retronas-romm-dirs.timer", dest: "/etc/systemd/system" }

    systemd_units:
      - { name: "retronas-romm-dirs", type: 'service', state: "stopped", enabled: "no", restart: "no", instance: "no" }
      - { name: "retronas-romm-dirs", type: 'timer',   state: "started", enabled: "yes", restart: "no", instance: "no" }

    # needs review or be handled in the flatten script  
    #internal_symlinks:
    #  - { src: 'sega/advancedpicobeena', dest: 'beena' }
    #  - { src: 'panasonic/3do', dest: 'panasonic-m2' }
    #  - { src: 'apple/pippin', dest: 'pippin' }
    #  - { src: 'interton/vc4000', dest: 'vc-4000' }
    #  - { src: 'tandy/vis', dest: 'vis' }
    #  - { src: 'tapwave/zodiac', dest: 'zod' }
    #    # 'amiga-cd',         # ??

  tasks:

    - name: "{{ my_name }} - Load RetroNAS config"
      ansible.builtin.include_vars: retronas_vars.yml

    - name: "{{ my_name }} - get update script"
      ansible.builtin.shell: curl -kLso "{{ script_dest }}" {{ script_url }}

    - name: "{{ my_name }} - make script executable"
      file:
        path: "{{ script_dest }}"
        mode: '0755'

    - ansible.builtin.import_role:
        name: retronas.role.romdir

    - ansible.builtin.import_role:
        name: retronas.role.samba

    - ansible.builtin.import_role:
        name: retronas.role.samba.system
      vars:
        nolink: true
        writable: "no"

    - ansible.builtin.import_role:
        name: retronas.role.templates

    - name: "{{ my_name }} - create startup service(s) instance"
      ansible.builtin.template:
        src: templates/{{ my_file }}/{{ item.name }}.{{ item.type }}.j2
        dest: /etc/systemd/system/{{ item.name }}.{{ item.type }}
        owner: root
        group: root
        mode: 0644
      with_items: "{{ systemd_units }}"
      notify: "{{ my_name }} daemon-reload"

    - name: "Import system-config role"
      ansible.builtin.import_role:
        name: retronas.role.system-config

    - name: Run flatten-romdir.sh for each src/dest (no top_level)
      ansible.builtin.shell: "{{ retronas_root }}/bin/flatten-romdir.sh {{ retronas_path }}/roms/{{ item.src }} {{ retronas_path }}/{{ system_key }}/roms/{{ item[system_key] }}"
      become: true
      loop: "{{ system_map }}"
      when: top_level_paths is defined and
            item[system_key] is defined and
            item[system_key] | length > 0

  handlers:

    - name: "{{ my_name }} daemon-reload"
      ansible.builtin.systemd:
        daemon_reload: true
