- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "apfs-fuse"
    - my_file: "install_apfs-fuse"
    - module_name: "apfs-fuse"
    - module_state: "present"

    - packages:
      - git
      - fuse 
      - libfuse3-dev 
      - bzip2 
      - libbz2-dev 
      - cmake 
      - g++ 
      - libattr1-dev 
      - zlib1g-dev

    - templates:
      - { name: "{{ my_file }}.sh", dest: "{{ retronas_root }}/scripts", mode: "0755"}

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    ansible.builtin.include_vars: retronas_vars.yml

  - ansible.builtin.import_role:
      name: retronas.role.package.latest

  -  ansible.builtin.import_role:
      name: retronas.role.templates

  - name: "{{ my_name }} - build source"
    ansible.builtin.command:
      cmd: "{{ retronas_root }}/scripts/{{ my_file }}.sh"
      creates: "{{ retronas_root }}/bin/apfs-fuse"

  -  ansible.builtin.import_role:
      name: retronas.role.system-config