---
- hosts: localhost
  gather_facts: true

  vars:
    my_name: "Telnet"
    my_file: "install_telnet"
    module_name: "telnet"

    templates:
      - { name: "telnet", dest: "/etc/xinetd.d", force: false }

    firewalld_rules:
      - { zone: "retro", service: "telnet" }

    packages:
      - telnet
      - telnetd
      - xinetd

  tasks:

    - name: "{{ my_name }} - Load RetroNAS config"
      ansible.builtin.include_vars: retronas_vars.yml

    - ansible.builtin.include_role:
        name: "{{ iroles }}"
      loop:
        - retronas.role.package.latest
        - retronas.role.templates
        - retronas.role.firewalld.port
        - retronas.role.system-config
      loop_control:
        loop_var: "iroles"

    - name: "{{ my_name }} - Enable startup services"
      ansible.builtin.service:
        name: xinetd
        state: started
        enabled: true
