---
- hosts: localhost
  gather_facts: no

  vars:
    my_name: "retrodeck CIFS"
    my_file: "install_retrodeck_cifs"
    module_name: "retrodeck_cifs"
    system_key: "retrodeck"

    top_level_paths:
      - { name: "roms",   enabled: yes,  generic: "roms",   systems: yes }
    #  - { name: "saves",  enabled: yes,  generic: "saves",  systems: yes }
      - { name: "bios",   enabled: yes,  generic: "bios",   systems: yes }

    internal_symlinks:
      - { src: 'commodore/amiga', dest: 'ags' }
      - { src: 'commodore/amiga', dest: 'amiga600' }
      - { src: 'capcom/cps1', dest: 'cps' }
      - { src: 'mame/mame', dest: 'mame-advmame' }
      - { src: 'nec/pcenginecd', dest: 'tg-cd' }
      - { src: 'sega/megacd', dest: 'segacd' }
      - { src: 'sega/megacd', dest: 'megacdjp' }
      - { src: 'sega/megadrive', dest: 'genesis' }
      - { src: 'sega/megadrive', dest: 'megadrivejp' }
      - { src: 'snk/neogeocd', dest: 'neogeocdjp' }
      - { src: 'sega/saturn', dest: 'saturnjp' }
      - { src: 'sega/32x', dest: 'sega32xjp' }
      - { src: 'sega/32x', dest: 'sega32xna' }
      - { src: 'nintendo/superfamicom', dest: 'sneshd' }
      - { src: 'nintendo/superfamicom', dest: 'snesna' }

  tasks:
    - name: "{{ my_name }} - Load RetroNAS config"
      ansible.builtin.include_vars: retronas_vars.yml

    - ansible.builtin.import_role:
        name: retronas.role.romdir

    - ansible.builtin.import_role:
        name: retronas.role.extradirs

    - ansible.builtin.import_role:
        name: retronas.role.samba

    - ansible.builtin.import_role:
        name: retronas.role.samba.system

    - ansible.builtin.import_role:
        name: retronas.role.system-config