- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "OpenSSH"
    - my_packages:
         - openssh-client
         - openssh-server
         - openssh-sftp-server

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - Install from repos"
    package:
       name: "{{ my_packages }}"
       state: latest
    notify:
    - Restart ssh

  - name: "{{ my_name }} - Enable startup services"
    service:
      name: ssh
      state: started
      enabled: yes

  handlers:

  - name: "{{ my_name }} - Restart ssh"
    service:
      name: ssh
      state: restarted

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "openssh"
    module_state: "present"