---
- hosts: localhost
  gather_facts: false

  vars:
    my_name: "assembly64"
    my_file: "install_{{ my_name }}"
    my_dir: /opt/{{ my_name }}
    module_name: "assembly64"
    module_state: "present"
    java_version: 26.0.1

    templates:
      - { name: "{{ my_file }}.sh", dest: "{{ retronas_root }}/scripts", mode: "0755" }
      - { name: "{{ my_name }}_retronas.sh", dest: "/opt/{{ my_name }}", mode: "0755" }

    paths:
      - { name: "{{ my_name }}", dest: "/opt", state: "directory", mode: "0755"}

    desktop_entries:
      - { filename: "/etc/X11/fluxbox/retronas-menu", option: "[exec] (Assembly64) { /opt/assembly64/assembly64_retronas.sh }", value: "", before: "[end]" }

  tasks:

    - name: "{{ my_name }} - Load RetroNAS config"
      ansible.builtin.include_vars: retronas_vars.yml

    - ansible.builtin.include_role:
        name: "{{ iroles }}"
      loop:
        - retronas.role.romdir
        - retronas.role.paths
        - retronas.role.templates
        - retronas.role.desktop
      loop_control:
        loop_var: "iroles"

    - name: "{{ my_name }} - disks symlink"
      ansible.builtin.file:
        src: "roms/apple/appleii"
        dest: "{{ retronas_path }}/{{ my_name }}"
        state: "link"

    - name: "{{ my_name }} - Install"
      ansible.builtin.shell: "{{ retronas_root }}/scripts/{{ my_file }}.sh 2>&1 | tee {{ retronas_root }}/log/{{ my_file }}.log"
      args:
        creates: "{{ retronas_root}} {{ my_dir }}/{{ my_file }}.sh"
      become: true

    - ansible.builtin.import_role:
        name: retronas.role.system-config

