---
- hosts: localhost
  gather_facts: false

  vars:
    my_name: "RetroArch Based Systems CIFS"
    my_file: "install_retroarch_cifs"
    module_name: "retroarch_cifs"
    system_key: "retroarch"

  tasks:
    - name: "{{ my_name }} - Load RetroNAS config"
      ansible.builtin.include_vars: retronas_vars.yml

    - ansible.builtin.include_role:
        name: "{{ iroles }}"
      loop:
        - retronas.role.romdir
        - retronas.role.samba
        - retronas.role.samba.system
        - retronas.role.system-config
      loop_control:
        loop_var: "iroles"
