---
- hosts: localhost
  gather_facts: false

  vars:
    my_name: "tftpd-hpa"
    my_file: "install_tftpd-hpa"
    module_name: "tftpd-hpa"

    firewalld_rules:
      - { zone: "retro", service: "tftp" }

    packages:
      tftpd-hpa

    templates:
      - { name: "tftpd-hpa", dest: "/etc/default" }

  tasks:
    - name: "{{ my_name }}  - Load RetroNAS config"
      ansible.builtin.include_vars: retronas_vars.yml

    - ansible.builtin.include_role:
        name: "{{ iroles }}"
      loop:
        - retronas.role.package.latest
        - retronas.role.templates
        - retronas.role.firewalld.port
      loop_control:
        loop_var: "iroles"

    - name: "{{ my_name }} - enable startup services"
      ansible.builtin.service:
        name: tftpd-hpa
        state: started
        enabled: true

    - ansible.builtin.import_role:
        name: retronas.role.system-config
