- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "open-iscsi"
    - my_file: "install_{{ my_name }}"
    - module_name: "open-iscsi"
    - module_state: "present"

    - packages:
        - open-iscsi

    - my_services:
        - open-iscsi

    - templates:
      - { name: "iscsi-manager-target-login.sh", dest: "{{ retronas_root }}/scripts", mode: "0755" }
    

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    ansible.builtin.include_vars: retronas_vars.yml

  - ansible.builtin.import_role:
      name: retronas.role.package.latest

  - ansible.builtin.import_role:
      name: retronas.role.templates

  - name: "{{ my_name }} - Enable startup services"
    ansible.builtin.service:
      name: ssh
      state: started
      enabled: yes

  - ansible.builtin.import_role:
      name: retronas.role.system-config