---
# Dependencies

- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "waybackproxy"
    - my_file: "install_{{ my_name }}"
    - my_dir: "/opt/{{ my_name }}"

    - systemd_units:
      - { name: "{{ my_name }}", type: 'service', state: "started", enabled: "no", restart: "yes", instance: "no" }

    - scripts:
      - { name: "install_waybackproxy.sh", dest: "{{ retronas_root }}/scripts" }

    - templates:
      - { name: "config.json", dest: "{{ my_dir }}" }
      - { name: "{{ my_name }}.service", dest: "/etc/systemd/system" }

    - packages:
      - git

    - paths:
      - { name: "{{ my_name }}", dest: "/opt",                state: "directory", mode: "0755" }

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - Install tools"
    package:
       name: "{{ packages }}"
       state: latest

  - name: "{{ my_name }} - paths"
    file:
      dest: "{{ item.dest }}/{{ item.name }}"
      owner: "{{ item.owner|default('root') }}"
      group: "{{ item.group|default('root') }}"
      mode: "{{ item.mode|default('0755') }}"
      state: "{{ item.state|default('directory') }}"
    with_items: "{{ paths }}"

  - name: "{{ my_name }} - scripts"
    template:
      src: "templates/{{ my_file }}/{{ item.name }}.j2"
      dest: "{{ item.dest }}/{{ item.name }}"
      owner: "{{ item.owner|default('root') }}"
      group: "{{ item.group|default('root') }}"
      mode: "{{ item.mode|default('0755') }}"
      force: "{{ item.force|default('yes') }}"
    with_items: "{{ scripts }}"

  - name: "{{ my_name }} - Install"
    shell: "{{ retronas_root }}/scripts/{{ my_file }}.sh 2>&1 | tee {{ retronas_root }}/log/{{ my_file }}.log"
    args:
      creates: "/opt/{{ my_name }}/{{ my_name }}.py"

  - name: "{{ my_name }} - templates"
    template:
      src: "templates/{{ my_file }}/{{ item.name }}.j2"
      dest: "{{ item.dest }}/{{ item.name }}"
      owner: "{{ item.owner|default('root') }}"
      group: "{{ item.group|default('root') }}"
      mode: "{{ item.mode|default('0644') }}"
      force: "{{ item.force|default('yes') }}"
    with_items: "{{ templates }}"

  - name: "{{ my_name }} - create startup service(s) instance"
    template:
      src: templates/{{ my_file }}/{{ item.name }}.{{ item.type }}.j2
      dest: /usr/lib/systemd/system/{{ item.name }}@.{{ item.type }}
      owner: root
      group: root
      mode: 0644
    with_items: "{{ systemd_units }}"
    notify: "{{ my_name }} - Restart service" 

  handlers:

  - name: "{{ my_name }} - Restart service"
    service:
      name: "{{ my_name }}.service"
      state: restarted
      daemon_reload: yes

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "waybackproxy"
    module_state: "present"