---
- hosts: localhost
  gather_facts: false

  vars:
    my_name: "OpenSSH"
    module_name: "openssh"

    packages:
      - openssh-client
      - openssh-server
      - openssh-sftp-server

    firewalld_rules:
      - { zone: retro, service: ssh }
      - { zone: modern, service: ssh }

  tasks:

    - name: "{{ my_name }} - Load RetroNAS config"
      ansible.builtin.include_vars: retronas_vars.yml

    - ansible.builtin.include_role:
        name: "{{ iroles }}"
      loop:
        - retronas.role.package.latest
        - retronas.role.firewalld.port
      loop_control:
        loop_var: "iroles"

    - name: "{{ my_name }} - Enable startup services"
      ansible.builtin.service:
        name: ssh
        state: restarted
        enabled: true

    - ansible.builtin.import_role:
        name: retronas.role.system-config
