---
- hosts: localhost
  gather_facts: false

  vars:
    - my_name: "tftpd-hpa"
    - my_file: "install_tftpd-hpa"
    - module_name: "tftpd-hpa"
    - module_state: "present"

    - firewalld_rules:
      - { zone: "retro", service: "tftp" }
    
    - packages:
        tftpd-hpa

    - templates:
      - { name: "tftpd-hpa", dest: "/etc/default" }

  tasks:
    - name: "{{ my_name }}  - Load RetroNAS config"
      ansible.builtin.include_vars: retronas_vars.yml

    - ansible.builtin.import_role:
        name: retronas.role.package.latest

    - ansible.builtin.import_role:
        name: retronas.role.templates

    - name: "{{ my_name }} - enable startup services"
      ansible.builtin.service:
        name: tftpd-hpa
        state: started
        enabled: true

    - ansible.builtin.import_role:
        name: retronas.role.firewalld.port

    - ansible.builtin.import_role:
        name: retronas.role.system-config

  handlers:

  - name: "{{ my_name }} - Restart service"
    ansible.builtin.service:
      name: tftpd-hpa
      state: restarted