# Dependencies
- import_playbook: install_cockpit.yml
- import_playbook: install_filesystems.yml
- import_playbook: install_extract-xiso.yml

- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "xboxmanager"
    - my_file: "install_xboxmanager"
    - my_path: "/opt"

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - clone repo"
    git:
      repo: 'https://github.com/sairuk/cockpit-xboxmanager.git'
      dest: "{{ my_path }}/xboxmanager"
      clone: yes
      update: yes
      version: "main"

  - name: "{{ my_name }} create device mounts dir"
    file: 
      path: "{{ retronas_path }}/device-mounts"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_group }}"
      mode: "0755"
      state: directory

  - name: "{{ my_name }} create device mount xbox dir"
    file: 
      path: "{{ retronas_path }}/device-mounts/xbox"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_group }}"
      mode: "0755"
      state: directory

  - name: "{{ my_name }} - run installer"
    command:
      cmd: "{{ my_path }}/xboxmanager/xboxmanager-install.sh"

  - name: "{{ my_name }} config file"
    template: 
      src: templates/{{ my_file }}/xboxmanager.cfg.j2
      dest: /opt/xboxmanager/xboxmanager.cfg
      owner: "{{ retronas_user }}"
      group: "{{ retronas_group }}"
      mode: '0644'

- import_playbook: retronas_system_config.yml
  vars:
    module_name: "xboxmanager"
    module_state: "present"