---
- hosts: localhost
  gather_facts: false

  vars:
    my_name: "MiSTer CIFS"
    my_file: "install_mister_cifs"
    module_name: "mister_cifs"
    system_key: "mister"
    system_key_dirs: true

    top_level_paths: &top_level_paths
      - { name: "games",      enabled: yes,  generic: "roms",        systems: yes }
      - { name: "saves",      enabled: yes,  generic: "saves",       systems: yes }
      - { name: "savestates", enabled: yes,  generic: "savestates",  systems: yes }
      - { name: "BIOS",       enabled: yes,  generic: "bios",        systems: yes }
      - { name: "wallpapers", enabled: yes,  generic: "wallpapers",  systems: no  }

    save_overrides:
      - { name: "GAMEBOY2P", src: "nintendo/gameboy2p" }
      - { name: "GBA2P", src: "nintendo/gameboyadvance2p" }

    templates:
      #  - { name: "retronas_mister.conf", dest: "/etc/samba" }
      - { name: "retronas-mister-dirs.service", dest: "/etc/systemd/system" }
      - { name: "retronas-mister-dirs.timer", dest: "/etc/systemd/system" }
      - { name: "retronas-mister-dirs.sh", dest: "{{ retronas_root }}/scripts", mode: "0755" }

    systemd_units:
      - { name: "retronas-mister-dirs", type: 'service', state: "stopped", enabled: "no", restart: "no", instance: "no" }
      - { name: "retronas-mister-dirs", type: 'timer',   state: "stopped", enabled: "no", restart: "no", instance: "no" }

    internal_symlinks:
      - { src: 'nintendo/gameandwatch',     dest: 'Game And Watch' }
      - { src: 'sega/gamegear',             dest: 'GameGear2P' }
      - { src: 'atari/st',                  dest: 'AtariSTUSERIO2' }
      - { src: 'nintendo/gameboyadvance',   dest: 'GBA_accuracy' }
      - { src: 'commodore/amiga',           dest: 'MinimigUSERIO2' }
      - { src: 'snk/neogeo',                dest: 'NeoGeo_24MHz_cpu_only' }
      - { src: 'sony/playstation1',         dest: 'PSX_DualSDRAM' }
      - { src: 'sega/saturn',               dest: 'Saturn_DualSDRAM' }
      - { src: 'sharp/x68000',              dest: 'X68000USERIO2' }
      - { src: 'other/intel_x86',           dest: 'ao486USERIO2' }

    system_symlinks:
      - { src: '{{ retronas_path }}/{{ system_key }}',           dest: '/media/fat' }

    dirs_only: false
    savedirs:
      - "saves"
      - "savestates"

  tasks:

    - name: "{{ my_name }} - Load RetroNAS config"
      ansible.builtin.include_vars: retronas_vars.yml

    - ansible.builtin.import_role:
        name: retronas.role.romdir

    - ansible.builtin.import_role:
        name: retronas.role.createdirs
      vars:
        top_level_paths: *top_level_paths

    - ansible.builtin.include_role:
        name: "{{ iroles }}"
      loop:
        - retronas.role.samba
        - retronas.role.samba.system
      loop_control:
        loop_var: "iroles"

    - name: "{{ my_name }} - create custom save directories"
      ansible.builtin.file:
        dest: "{{ retronas_path }}/{{ item.1 }}/{{ item.0.src|lower }}"
        state: directory
        mode: '2775'
        owner: "{{ retronas_user }}"
        group: "{{ retronas_group }}"
      loop: "{{ save_overrides|product(savedirs)|list }}"

    - name: "{{ my_name }} - create custom save links"
      ansible.builtin.file:
        src: "../../{{ item.1 }}/{{ item.0.src|lower }}"
        dest: "{{ retronas_path }}/{{ system_key }}/{{ item.1 }}/{{ item.0.name }}"
        state: link
      loop: "{{ save_overrides|product(savedirs)|list }}"

    - name: "{{ my_name }} - create system links"
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ system_symlinks }}"

    - ansible.builtin.import_role:
        name: retronas.role.templates
      when: dirs_only is false

    - name: "daemon-reload"
      ansible.builtin.systemd_service:
        daemon_reload: true

    - ansible.builtin.import_role:
        name: retronas.role.system-config
