- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "RetroNAS filesystems"
    - my_file: "install_filesystems"

    - my_packages:
      - btrfs-progs
      - ntfs-3g
      - exfatprogs
      - exfat-fuse
      - hfsplus
      - xfsprogs
      - nfs-common
      - e2fsprogs
      - dosfstools
      #- curlftpfs
      - sshfs
      - udisks2
      - udisks2-btrfs
      - udisks2-lvm2
      - udisks2-zram

  tasks:

  - name: "{{ my_name }} - install packages"
    ansible.builtin.apt:
      name: "{{ my_packages }}"
      state: latest

- ansible.builtin.import_playbook: retronas_system_config.yml
  vars:
    module_name: "filesystems"
    module_state: "present"