# Dependencies
- ansible.builtin.import_playbook: install_romdir.yml
- ansible.builtin.import_playbook: install_extradirs.yml

- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "smbmounter"
    - my_file: "install_{{ my_name }}"

  tasks:

  - name: "{{ my_name }} - Include systems map"
    ansible.builtin.include_vars: "retronas_systems.yml"

  - name: "{{ my_name }} - Load RetroNAS config"
    ansible.builtin.include_vars: retronas_vars.yml

  - name: "{{ my_name }} - link romdir"
    ansible.builtin.file:
      src: "{{ retronas_path }}/roms/commodore/amiga"
      dest: "{{ retronas_path }}/amiga"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_group }}"
      state: link
      mode: "0775"
    notify: "{{ my_name }} - Install Samba"

  - name: "{{ my_name }} - configure includes file"
    ansible.builtin.ini_file:
      path: /etc/samba/smb.conf
      section: "amiga"
      option: "include"
      value: "/etc/samba/retronas_amiga.conf"
    notify: "{{ my_name }} - Install Samba"

  - name: "{{ my_name }} - configure retro shares"
    ansible.builtin.template:
      src: "templates/{{ my_file }}/retronas_{{ my_name }}.conf.j2"
      dest: /etc/samba/retronas_amiga.conf
      owner: root
      group: root
      mode: '0644'
    notify: "{{ my_name }} - Install Samba"

  handlers:

  - name: "{{ my_name }} - Install Samba"
    ansible.builtin.set_fact:
      install_changed: true

- ansible.builtin.import_playbook: install_samba.yml
  vars:
    changed: "{{ install_changed }}"
  when: install_changed is defined and
        install_changed is true

- ansible.builtin.import_playbook: retronas_system_config.yml
  vars:
    module_name: "recalbox_cifs"
    module_state: "present"