- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "affstools"
    - my_file: "install_{{ my_name }}"

    - packages:
      - make
      - autoconf
      - gcc
      - curl
      - build-essential

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    ansible.builtin.include_vars: retronas_vars.yml

  - name: "{{ my_name }} - Install build tools"
    ansible.builtin.package:
       name: "{{ packages }}"
       state: latest

  - name: "{{ my_name }} - Generate {{ my_file }} script"
    ansible.builtin.template:
      src: "templates/{{ my_file }}/{{ my_file }}.sh.j2"
      dest: "{{ retronas_root }}/scripts/{{ my_file }}.sh"
      owner: root
      group: root
      mode: 0755

  - name: "{{ my_name }} - Install from source code"
    ansible.builtin.shell: "{{ retronas_root }}/scripts/{{ my_file }}.sh 2>&1 | tee {{ retronas_root }}/log/{{ my_file }}.log"
    args:
      creates: "/usr/local/sbin/mkaffs"

- ansible.builtin.import_playbook: retronas_system_config.yml
  vars:
    module_name: "affstools"
    module_state: "present"