---
- hosts: localhost
  gather_facts: yes

  vars:
    my_name: "dreampi"
    my_file: "install_dreampi"
    module_name: "dreampi"

    packages:
      - git
      - dnsmasq 
      - dnsutils 
      - libnetfilter-queue-dev
      - libnetfilter-queue1 
      - ppp
      - arping 
      - nftables 
      - tcpd 
      - wvdial 
      - python3-pip

    groups:
      - dialout
      - dip

    templates:
      - { name: "{{ my_file }}.sh", dest: "{{ retronas_root }}/scripts", mode: "0755" }
      - { name: "{{ my_name }}.conf", dest: "/etc/dnsmasq.d", force: no }

    paths:
      - { name: "dnsmasq.d", dest: "/etc" }

    systemd_patches:
      - { unit: "dreampi.service", line: "Restart=on-failure", regex: "^Restart=on-failure$", after: "^ExecStart=.*$" }
      - { unit: "dreampi.service", line: "RestartSec=30s", regex: "^RestartSec=.+", after: "^Restart=.*$" }

  tasks:

  - name: "{{ my_name }} - Checking hw platform compatiblity"
    ansible.builtin.debug:
      msg: "INCOMPATIBLE PLATFORM, only arm platforms are supported"
    when: ansible_architecture is not search('arm') and
          ansible_architecture != 'aarch64'

  - ansible.builtin.meta: end_play
    when: ansible_architecture is not search('arm') and
          ansible_architecture != 'aarch64'

  - name: "{{ my_name }} - Load RetroNAS config"
    ansible.builtin.include_vars: retronas_vars.yml

  - ansible.builtin.import_role:
      name: retronas.role.package.latest

  - ansible.builtin.import_role:
      name: retronas.role.paths 

  - ansible.builtin.import_role:
      name: retronas.role.templates

  - name: "{{ my_name }} - Run installer"
    ansible.builtin.shell:
      cmd: "./{{ my_file }}.sh 2>&1 | tee {{ retronas_root }}/log/{{ my_file }}.log"
      chdir: "{{ retronas_root }}/scripts"
      executable: /bin/bash
    notify: "{{ my_name }} Restart Services"

  - name: "{{ my_name }} - Patch systemd service"
    ansible.builtin.lineinfile:
      path: /etc/systemd/system/{{ item.unit }}
      regex: "{{ item.regex }}"
      insertafter: "{{ item.after }}"
      line: "{{ item.line }}"
      state: present
    with_items: "{{ systemd_patches }}"
    notify: "{{ my_name }} Restart Services"

  - ansible.builtin.import_role:
      name: retronas.role.system-config

  handlers:
  - name: "{{ my_name }} Restart Services"
    ansible.builtin.service:
      name: "{{ item }}"
      state: started
      enabled: yes
      daemon_reload: yes
    with_items:
      - "{{ my_name }}.service"