---
- hosts: localhost
  gather_facts: false

  vars:
    my_name: "rclone"
    my_file: "install_rclone"
    module_name: "rclone"

    packages:
      - rclone

    templates:
      - { name: "{{ my_name }}-webui.service", dest: "/etc/systemd/system", mode: "0644" }

    services:
      - "{{ my_name }}-webui.service"

    firewalld_ports:
      - { port: 5572, protocol: tcp, zone: retro }
      - { port: 5572, protocol: tcp, zone: modern }

  tasks:

    - name: "{{ my_name }} - Load RetroNAS config"
      ansible.builtin.include_vars: retronas_vars.yml

    - ansible.builtin.include_role:
        name: "{{ iroles }}"
      loop:
        - retronas.role.package.latest
        - retronas.role.templates
        - retronas.role.htpasswd
        - retronas.role.firewalld.port
        - retronas.role.system-config
      loop_control:
        loop_var: "iroles"

    - name: "{{ my_name }} - Restart service"
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
        state: restarted
        daemon_reload: true
      loop: "{{ services }}"
