# Dependencies

- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "pandoc"
    - my_file: "install_pandoc"

    - packages:
      - pandoc

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    ansible.builtin.include_vars: retronas_vars.yml

  - name: "{{ my_name }} - Install packages"
    package:
       name: "{{ packages }}"
       state: latest

- ansible.builtin.import_playbook: retronas_system_config.yml
  vars:
    module_name: "pandoc"
    module_state: "present"