---
- hosts: localhost
  gather_facts: false

  vars:
    my_name: "mc"
    my_file: "install_mc"
    module_name: "mc"

    packages:
      - mc

  tasks:

    - name: "{{ my_name }} - Load RetroNAS config"
      ansible.builtin.include_vars: retronas_vars.yml

    - ansible.builtin.include_role:
        name: "{{ iroles }}"
      loop:
        - retronas.role.package.latest
        - retronas.role.system-config
      loop_control:
        loop_var: "iroles"
