- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "ProFTPd"

    - my_packages:
       - avahi-daemon
       - proftpd-core

  tasks:

  - name: "{{ my_name }}  - Load RetroNAS config"
    ansible.builtin.include_vars: retronas_vars.yml

  - name: "{{ my_name }}  - install from repos"
    ansible.builtin.package:
       name: "{{ my_packages }}"
       state: latest

  - name: "{{ my_name }} - remove  mod_unique_id.c"
    ansible.builtin.ini_file:
      path: /etc/proftpd/modules.conf
      section: null
      option: "LoadModule mod_unique_id.c"
      state: absent
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - configure retro shares"
    ansible.builtin.template:
      src: templates/install_proftpd/retronas.conf.j2
      dest: /etc/proftpd/conf.d/retronas.conf
      owner: root
      group: root
      mode: '0644'
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - configure avahi"
    ansible.builtin.template:
      src: templates/install_proftpd/ftp.service.j2
      dest: /etc/avahi/services/ftp.service
      owner: root
      group: root
      mode: '0644'
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - enable startup services"
    ansible.builtin.service:
      name: proftpd
      state: started
      enabled: yes

  handlers:

  - name: "{{ my_name }} - Restart service"
    ansible.builtin.service:
      name: "{{ item }}"
      state: restarted
    with_items:
      - avahi-daemon
      - proftpd

- ansible.builtin.import_playbook: retronas_system_config.yml
  vars:
    module_name: "proftpd"
    module_state: "present"