- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "troubleshooting"
    - my_file: "install_troubleshooting"

    - packages:
      - ioping
      - iotop
      - iperf3
      - tcpdump
      - iftop
      - traceroute
      - ethtool
      - socat
      - nmap
      - bind9-dnsutils
      - mtr
      - strace
      - curl
      - smartmontools
      - htop

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    ansible.builtin.include_vars: retronas_vars.yml

  - ansible.builtin.import_role:
      name: retronas.role.package.latest

- ansible.builtin.import_playbook: retronas_system_config.yml
  vars:
    module_name: "troubleshooting"
    module_state: "present"