---
- hosts: localhost
  gather_facts: false

  vars:
    my_name: "Disable Laptop Lid"
    my_file: "install_disable-laptop-lid"
    service: "systemd-logind.service"
    module_name: "disable-laptop-lid"

    paths:
      - { name: "logind.conf.d", dest: "/etc/systemd/",                state: "directory", mode: "0755"}

    templates:
      - { name: "retronas.conf", dest: "/etc/systemd/logind.conf.d", mode: "0755"}

  tasks:

    - name: "{{ my_name }} - Load RetroNAS config"
      ansible.builtin.include_vars: retronas_vars.yml

    - ansible.builtin.include_role:
        name: "{{ iroles }}"
      loop:
        - retronas.role.paths
        - retronas.role.templates
        - retronas.role.system-config
      loop_control:
        loop_var: "iroles"

    - name: "{{ my_name }} - Restart service"
      ansible.builtin.service:
        name: "{{ service }}"
        state: restarted
        enabled: true
        daemon_reload: true
