---
- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "ucon64"
    - my_file: "install_ucon64"

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    ansible.builtin.include_vars: retronas_vars.yml

  - name: "{{ my_name }} - Install build tools"
    ansible.builtin.apt:
       name: "{{ item }}"
       state: latest
    with_items:
      - make
      - gcc
      - coreutils

  - name: "{{ my_name }} - Generate scripts"
    ansible.builtin.template:
      src: "templates/{{ my_file }}/{{ my_file }}.sh.j2"
      dest: "{{ retronas_root }}/scripts/{{ my_file }}.sh"
      owner: root
      group: root
      mode: 0755

  - name: "{{ my_name }} - build source"
    ansible.builtin.command:
      cmd: "{{ retronas_root }}/scripts/{{ my_file }}.sh"
      creates: "/usr/local/bin/ucon64"

- ansible.builtin.import_playbook: retronas_system_config.yml
  vars:
    module_name: "ucon64"
    module_state: "present"