---
- hosts: localhost
  gather_facts: no

  vars:
    my_name: "OpenSSH"
    module_name: "openssh"

    packages:
         - openssh-client
         - openssh-server
         - openssh-sftp-server

    firewalld_rules:
      - { zone: retro, service: ssh }
      - { zone: modern, service: ssh }

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    ansible.builtin.include_vars: retronas_vars.yml

  - ansible.builtin.import_role:
      name: retronas.role.package.latest
    notify: "{{ my_name }} - Restart ssh"

  - name: "{{ my_name }} - Enable startup services"
    ansible.builtin.service:
      name: ssh
      state: started
      enabled: yes

  - ansible.builtin.import_role:
      name: retronas.role.firewalld.port

  - ansible.builtin.import_role:
      name: retronas.role.system-config

  handlers:

  - name: "{{ my_name }} - Restart ssh"
    ansible.builtin.service:
      name: ssh
      state: restarted