- hosts: localhost
  gather_facts: no


  vars:
    - my_name: "macproxy"
    - my_file: "install_macproxy"
    - module_name: "macproxy"
    - module_state: "present"

    - packages:
      - python3 
      - python3-venv
      - python3-pip

    - templates:
      - { name: "{{ my_name }}.service", dest: "/etc/systemd/system" }

    - repo: https://github.com/rdmark/macproxy.git

    - firewalld_ports:
      - { port: 5000, protocol: tcp }

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    ansible.builtin.include_vars: retronas_vars.yml

  - ansible.builtin.import_role:
      name: retronas.role.package.latest

  - name: "{{ my_name }} - clone repo"
    ansible.builtin.git:
      repo: "{{ repo }}"
      dest: /opt/{{ my_name }}

  - ansible.builtin.import_role:
      name: retronas.role.templates

  - ansible.builtin.import_role:
      name: retronas.role.firewalld.port

  - ansible.builtin.import_role:
      name: retronas.role.system-config

  handlers:
  - name: "{{ my_name }} Restart Services"
    ansible.builtin.service:
      name: "{{ my_name }}.service"
      state: started
      enabled: yes
      daemon_reload: yes