# Dependencies
- ansible.builtin.import_playbook: install_romdir.yml
- ansible.builtin.import_playbook: install_extradirs.yml

- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "smbmounter"
    - my_file: "install_{{ my_name }}"
    - module_name: "smbmounter"

    - templates:
      - { name: "retronas_{{ my_name }}.conf", dest: "/etc/samba" }

  tasks:

  - name: "{{ my_name }} - Include systems map"
    ansible.builtin.include_vars: "retronas_systems.yml"

  - name: "{{ my_name }} - Load RetroNAS config"
    ansible.builtin.include_vars: retronas_vars.yml

  - ansible.builtin.import_role:
      name: retronas.role.samba

  - name: "{{ my_name }} - link romdir"
    ansible.builtin.file:
      src: "{{ retronas_path }}/roms/commodore/amiga"
      dest: "{{ retronas_path }}/amiga"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_group }}"
      state: link
      mode: "0775"

  - name: "{{ my_name }} - configure includes file"
    ansible.builtin.ini_file:
      path: /etc/samba/smb.conf
      section: "amiga"
      option: "include"
      value: "/etc/samba/retronas_amiga.conf"

  - ansible.builtin.import_role:
      name: retronas.role.templates

  - ansible.builtin.import_role:
      name: retronas.role.system-config