---
- hosts: localhost
  gather_facts: no

  vars:
    my_name: "affstools"
    my_file: "install_{{ my_name }}"
    module_name: "affstools"

    packages:
      - make
      - autoconf
      - gcc
      - curl
      - build-essential

    templates:
      - { name: "{{ my_file }}.sh", dest: "{{ retronas_root }}/scripts", mode: "0755"}

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    ansible.builtin.include_vars: retronas_vars.yml

  - ansible.builtin.import_role:
      name: retronas.role.package.latest

  -  ansible.builtin.import_role:
      name: retronas.role.templates

  - name: "{{ my_name }} - Install from source code"
    ansible.builtin.shell: "{{ retronas_root }}/scripts/{{ my_file }}.sh 2>&1 | tee {{ retronas_root }}/log/{{ my_file }}.log"
    args:
      creates: "/usr/local/sbin/mkaffs"

  -  ansible.builtin.import_role:
      name: retronas.role.system-config