---
- hosts: localhost
  gather_facts: false

  vars:
    my_name: "EmuElec CIFS"
    my_file: "install_emuelec_cifs"
    module_name: "emuelec_cifs"
    system_key: "emuelec"
    system_key_dirs: true

    internal_symlinks:
      - { src: 'nintendo/famicom', dest: 'nesh' }
      - { src: 'nintendo/gameboyadvance', dest: 'gbah' }
      - { src: 'nintendo/gameboy', dest: 'gbh' }
      - { src: 'nintendo/gameboycolor', dest: 'gbch' }      
      - { src: 'nintendo/superfamicom', dest: 'snesh' }
      - { src: 'sega/gamegear', dest: 'gamegearh' }
      - { src: 'sega/megadrive', dest: 'genh' }

  tasks:
    - name: "{{ my_name }} - Load RetroNAS config"
      ansible.builtin.include_vars: retronas_vars.yml

    - ansible.builtin.include_role:
        name: "{{ iroles }}"
      loop:
        - retronas.role.romdir
        - retronas.role.samba
        - retronas.role.samba.system
        - retronas.role.system-config
      loop_control:
        loop_var: "iroles"
