- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "EccEDC"
    - my_file: "install_eccedc"
    - module_name: "eccedc"
    - module_state: "present"

    - packages:
      - coreutils
      - make
      - gcc
      - g++
      - curl
      - build-essential
      - unzip

    - templates:
      - { name: "{{ my_file }}.sh", dest: "{{ retronas_root }}/scripts", mode: "0755"}

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    ansible.builtin.include_vars: retronas_vars.yml

  - ansible.builtin.import_role:
      name: retronas.role.package.latest

  - ansible.builtin.import_role:
      name: retronas.role.templates

  - name: "{{ my_name }} - Run installer"
    ansible.builtin.shell:
      cmd: "./{{ my_file }}.sh 2>&1 | tee {{ retronas_root }}/log/{{ my_file }}.log"
      chdir: "{{ retronas_root }}/scripts"
      executable: /bin/bash

  - ansible.builtin.import_role:
      name: retronas.role.system-config