---
# Dependencies
- ansible.builtin.import_playbook: install_extract-xiso.yml

- hosts: localhost
  gather_facts: yes

  roles:
    - retronas.role.cockpit
    - retronas.role.filesystems
    - retronas.role.curlftpfs

  vars:
    my_name: "xboxmanager"
    my_file: "install_xboxmanager"
    my_path: "/opt"
    module_name: "xboxmanager"

    paths:
      - { name: "device-mounts",  dest: "{{ retronas_path }}",                owner: "{{ retronas_user }}", group: "{{ retronas_group }}" }
      - { name: "xbox",           dest: "{{ retronas_path }}/device-mounts",  owner: "{{ retronas_user }}", group: "{{ retronas_group }}" }

    templates:
      - { name: "xboxmanager.cfg", dest: "/opt/xboxmanager", owner: "{{ retronas_user }}", group: "{{ retronas_group }}" }

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    ansible.builtin.include_vars: retronas_vars.yml

  - name: "{{ my_name }} - clone repo"
    ansible.builtin.git:
      repo: 'https://github.com/sairuk/cockpit-xboxmanager.git'
      dest: "{{ my_path }}/xboxmanager"
      clone: yes
      update: yes
      version: "main"

  - ansible.builtin.import_role:
      name: retronas.role.paths

  - name: "{{ my_name }} - run installer"
    ansible.builtin.command:
      cmd: "{{ my_path }}/xboxmanager/xboxmanager-install.sh"

  - ansible.builtin.import_role:
      name: retronas.role.templates

  - ansible.builtin.import_role:
      name: retronas.role.system-config