# Dependencies
- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "dhcpcd"
    - my_file: "install_{{ my_name }}"

    - packages:
      - dhcpcd

    - changed: false

  tasks:

  - name: "{{ my_name }} - Install packages"
    package:
       name: "{{ packages }}"
       state: latest

  - name: "{{ my_name }} - restart if imported because handlers will not run"
    service:
      name: "{{ item }}"
      state: restarted
      enabled: yes
    with_items: "{{ my_services }}"
    when: changed is true


- import_playbook: retronas_system_config.yml
  vars:
    module_name: "dhcpcd"
    module_state: "present"