---
- hosts: localhost
  gather_facts: false

  vars:
    my_name: "analoguepocket CIFS"
    my_file: "install_analoguepocket_cifs"
    module_name: "analoguepocket_cifs"
    system_key: "analoguepocket"
    system_key_dirs: true

    top_level_paths: &top_level_paths
      - { name: "Assets",       enabled: yes,  generic: "roms",   systems: yes }
      - { name: "Cores",        enabled: yes,  generic: "",       systems: no }
      - { name: "Platforms",    enabled: yes,  generic: "",       systems: no }
      - { name: "Presets",      enabled: yes,  generic: "",       systems: no }
      - { name: "Saves",        enabled: yes,  generic: "",       systems: no }

  tasks:

    - name: "{{ my_name }} - Load RetroNAS config"
      ansible.builtin.include_vars: retronas_vars.yml

    - ansible.builtin.import_role:
        name: retronas.role.romdir
      vars:
        top_level_paths: *top_level_paths

    - ansible.builtin.import_role:
        name: retronas.role.samba

    - ansible.builtin.import_role:
        name: retronas.role.samba.system

    - ansible.builtin.import_role:
        name: retronas.role.system-config
