- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "far2l"
    - my_file: "install_{{ my_name }}"
    - module_name: "far2l"

    - packages:
      - gawk 
      - m4
      - libpcre3-dev 
      - libxerces-c-dev 
      - libspdlog-dev 
      - libuchardet-dev
      - libssh-dev 
      - libssl-dev 
      - libsmbclient-dev 
      - libnfs-dev 
      - libneon27-dev 
      - libarchive-dev 
      - cmake 
      - g++
      - gcc
      - git

    - templates:
      - { name: "{{ my_file }}.sh", dest: "{{ retronas_root }}/scripts", mode: "0755" }

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    ansible.builtin.include_vars: retronas_vars.yml

  - ansible.builtin.import_role:
      name: retronas.role.package.latest

  - ansible.builtin.import_role:
      name: retronas.role.templates

  - name: "{{ my_name }} - build source"
    ansible.builtin.command:
      cmd: "{{ retronas_root }}/scripts/{{ my_file }}.sh"

  - ansible.builtin.import_role:
      name: retronas.role.system-config