---
- hosts: localhost
  gather_facts: true

  vars:
    my_name: "mtcp-netdrive"
    my_file: "install_mtcp-netdrive"
    module_name: "mtcp-netdrive"

    packages:
      - screen
      - curl
      - unzip

    paths:
      - { name: "{{ my_name }}", dest: "/opt", state: "directory", mode: "0755", owner: "{{ retronas_user }}", group: "{{ retronas_group }}" }

    templates:
      - { name: "install_mtcp-netdrive.sh", dest: "{{ retronas_root }}/scripts", mode: "0755", force: "yes" }
      - { name: "mtcp-netdrive.service", dest: "/etc/systemd/system", force: "yes" }
      - { name: "mtcp-netdrive.sh", dest: "{{ retronas_root }}/scripts", mode: "0755", force: "yes" }

    firewalld_rules:
      - { zones: retro, service: mtcp-netdrive }

    firewalld_templates:
      - mtcp-netdrive

    my_services:
      - mtcp-netdrive

  tasks:

    - name: "{{ my_name }} - Load RetroNAS config"
      ansible.builtin.include_vars: retronas_vars.yml

    - ansible.builtin.include_role:
        name: "{{ iroles }}"
      loop:
        - retronas.role.package.latest
        - retronas.role.paths
        - retronas.role.templates
        - retronas.role.firewalld.port
      loop_control:
        loop_var: "iroles"

    - name: "{{ my_name }} - install mtcp-netdrive"
      ansible.builtin.command:
        cmd: "{{ retronas_root }}/scripts/{{ my_file }}.sh"

    - name: "{{ my_name }} - enable startup services"
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
        daemon-reload: true
      with_items: "{{ my_services }}"

    - ansible.builtin.import_role:
        name: retronas.role.system-config
