---
- hosts: localhost
  gather_facts: no

  vars:
    my_name: "ProFTPd"
    my_file: "install_proftpd"
    module_name: "proftpd"

    packages:
       - avahi-daemon
       - proftpd-core

    templates:
      - { name: "retronas.conf", dest: "/etc/proftpd/conf.d" }
      - { name: "ftp.service", dest: "/etc/avahi/services" }

    firewalld_rules:
      - { name: ftp, zone: retro }
      - { name: ftp, zone: modern }

  tasks:

  - name: "{{ my_name }}  - Load RetroNAS config"
    ansible.builtin.include_vars: retronas_vars.yml

  - ansible.builtin.import_role:
      name: retronas.role.package.latest

  - ansible.builtin.import_role:
      name: retronas.role.templates

  - name: "{{ my_name }} - remove  mod_unique_id.c"
    ansible.builtin.ini_file:
      path: /etc/proftpd/modules.conf
      section: null
      option: "LoadModule mod_unique_id.c"
      state: absent
    notify: "{{ my_name }} - Restart service"

  - name: "{{ my_name }} - enable startup services"
    ansible.builtin.service:
      name: proftpd
      state: started
      enabled: yes

  - ansible.builtin.import_role:
      name: retronas.role.firewalld.port

  - ansible.builtin.import_role:
      name: retronas.role.system-config

  handlers:

  - name: "{{ my_name }} - Restart service"
    ansible.builtin.service:
      name: "{{ item }}"
      state: restarted
    with_items:
      - avahi-daemon
      - proftpd
