---
- hosts: localhost

  vars:
    my_name: "MiSTer Organize"
    my_file: "install_mister-organize"
    module_name: "mister-organize"

    packages:
      - git
      - curl
      - unzip
      - mono-complete

    paths:
      - { name: "mister-organize", dest: "{{ retronas_path }}", owner: "{{ retronas_user }}", group: "{{ retronas_group }}" }
      - { name: "romimport", dest: "{{ retronas_path }}", owner: "{{ retronas_user }}", group: "{{ retronas_group }}" }

    templates:
      - { name: "{{ my_file }}.sh", dest: "{{ retronas_root }}/scripts", mode: "0755", force: true}
      - { name: "mister-organize.sh", dest: "{{ retronas_root }}/scripts", mode: "0755"}
      - { name: "mister-organize-gui.sh", dest: "/usr/local/bin", owner: "{{ retronas_user }}", group: "{{ retronas_group }}", mode: "0755" }

    desktop_entries:
      - { filename: "/etc/X11/fluxbox/retronas-menu", option: "[exec] (ROMVault) { /usr/local/bin/mister-organize-gui.sh }", value: "", before: "[end]" }

  tasks:

    - ansible.builtin.assert:
        that: ansible_architecture == "x86_64"
        fail_msg: "Unsupported architecture"

    - name: "{{ my_name }} - Load RetroNAS config"
      ansible.builtin.include_vars: retronas_vars.yml

    - name: "{{ my_name }} - Load RetroNAS Systems"
      ansible.builtin.include_vars: retronas_systems.yml

    - ansible.builtin.include_role:
        name: "{{ iroles }}"
      loop:
        - retronas.role.romdir
        - retronas.role.package.latest
        - retronas.role.paths
        - retronas.role.templates
        - retronas.role.desktop
      loop_control:
        loop_var: "iroles"

    - name: "{{ my_name }} - Install from project repo"
      ansible.builtin.git:
        repo: "https://github.com/MiSTerOrganize/MiSTerOrganize.git"
        dest: "{{ retronas_path}}/{{ module_name }}"
        single_branch: true
        clone: true
        update: true
        force: true

    - name: "{{ my_name }} - setup local"
      ansible.builtin.shell: "{{ retronas_root }}/scripts/{{ my_file }}.sh 2>&1"

    - ansible.builtin.include_role:
        name: "{{ iroles }}"
      loop:
        - retronas.role.system-config
        - retronas.role.samba
      loop_control:
        loop_var: "iroles"

    - ansible.builtin.import_role:
        name: retronas.role.samba.system
      vars:
        system_key: "{{ module_name }}"
