---
- hosts: localhost
  gather_facts: false

  vars:
    my_name: "troubleshooting"
    my_file: "install_troubleshooting"
    module_name: "troubleshooting"

    packages:
      - ioping
      - iotop
      - iperf3
      - tcpdump
      - iftop
      - traceroute
      - ethtool
      - socat
      - nmap
      - bind9-dnsutils
      - mtr
      - strace
      - curl
      - smartmontools
      - htop

  tasks:

    - name: "{{ my_name }} - Load RetroNAS config"
      ansible.builtin.include_vars: retronas_vars.yml

    - ansible.builtin.include_role:
        name: "{{ iroles }}"
      loop:
        - retronas.role.package.latest
        - retronas.role.system-config
      loop_control:
        loop_var: "iroles"
