# Dependencies

- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "linux-gadgets"
    - my_file: "install_{{ my_name }}"

    - templates:
      - { name: "gadget-mass-storage-manage.sh", dest: "{{ retronas_root }}/scripts", mode: "0755"}

    - paths:
      - { name: "images", dest: "{{ retronas_path }}", state: "directory", mode: "0755", owner: "{{ retronas_user }}", group: "{{ retronas_group }}"}

  tasks:

  - name: "{{ my_name }} - Include systems map"
    ansible.builtin.include_vars: "retronas_systems.yml"

  - name: "{{ my_name }} - Load RetroNAS config"
    ansible.builtin.include_vars: retronas_vars.yml

  - ansible.builtin.import_role:
      name: retronas.role.paths

  - ansible.builtin.import_role:
      name: retronas.role.templates

- ansible.builtin.import_playbook: retronas_system_config.yml
  vars:
    module_name: "linux-gadgets"
    module_state: "present"