---
- hosts: localhost
  gather_facts: false

  vars:
    module_name: "romdir"

  tasks:
    - ansible.builtin.include_role:
        name: "{{ iroles }}"
      loop:
        - retronas.role.romdir
        - retronas.role.system-config
      loop_control:
        loop_var: "iroles"
