- hosts: localhost
  gather_facts: no

  vars:
    - my_name: "DVDAuth"
    - my_file: "install_dvdauth"

    - my_packages:
      - git
      - coreutils
      - make
      - gcc
      - g++
      - curl
      - build-essential
      - unzip
      - util-linux

  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    ansible.builtin.include_vars: retronas_vars.yml

  - name: "{{ my_name }} - Install dependencies"
    ansible.builtin.package:
       name: "{{ my_packages }}"
       state: latest

  - name: "{{ my_name }} - Prepare installer script"
    ansible.builtin.template:
      src: templates/{{ my_file }}/{{ my_file }}.sh.j2
      dest: "{{ retronas_root }}/scripts/{{ my_file }}.sh"
      owner: root
      group: root
      mode: 0755

  - name: "{{ my_name }} - Run installer"
    ansible.builtin.shell:
      cmd: "./{{ my_file }}.sh 2>&1 | tee {{ retronas_root }}/log/{{ my_file }}.log"
      chdir: "{{ retronas_root }}/scripts"
      executable: /bin/bash

- ansible.builtin.import_playbook: retronas_system_config.yml
  vars:
    module_name: "dvdauth"
    module_state: "present"