---
package_map:
  - { retronas: "aria2", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "arping", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "autoconf", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "autotools-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "avahi-daemon", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "avahi-utils", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "bind9-dnsutils", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "bison", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "bridge-utils", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "btrfs-progs", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "build-essential", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "bzip2", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "ca-certificates", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "chromium", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "ckermit", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "cmake", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "cockpit", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "cockpit-networkmanager", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "cockpit-storaged", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "coreutils", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "curl", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "default-jre", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "deluge-console", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "deluge-web", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "deluged", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "dhcpcd", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "disktype", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "dnsmasq", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "dnsutils", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "dosfstools", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "dosfstools", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "e2fsprogs", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "ethtool", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "exfat-fuse", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "exfatprogs", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "expect", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "ffmpeg", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "firewalld", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "flex", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "fuse", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "g++", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "gawk", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "gcc", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "genisoimage", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "geoip-bin", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "geop-database", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "gettext", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "git", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "gnugp", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "hdparm", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "hfsplus", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "hfsutils", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "hostapd", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "htop", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "iftop", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "imagemagick", debian12: "imagemagick-6.q16", debian13: "imagemagick-7.q16", fedora41: "", ubuntu: "" }
  - { retronas: "imagemagick-common", debian12: "imagemagick-6-common", debian13: "imagemagick-7-common", fedora41: "", ubuntu: "" }
  - { retronas: "ioping", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "iotop", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "iperf3", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "jq", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "kpartx", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libacl1", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libacl1-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libarchive-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libattr1", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libattr1-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libavahi-client-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libavahi-client3", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libavahi-common-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libavahi-common3", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libavahi-core-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libbz2-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libc6", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libcmark-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libcomerr2", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libcrack2", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libcups2", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libcups2-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libcurl4-openssl-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libcurl4-openssl-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libdb++-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libdb-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libdb5.3", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libdbus-1-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libdbus-glib-1-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libev-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libevdev2", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libevent-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libfuse-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libfuse3-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libgcrypt-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libgcrypt20", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libgcrypt20-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libglib2.0-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libgmock-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libgssapi-krb5-2", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libiniparser-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libio-socket-inet6-perl", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libk5crypto3", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libkrb5-3", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libkrb5-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libldap-2.4-2", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libltdl-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libmbedtls", debian12: "libmbedtls14", debian13: "libmbedtls21", fedora41: "", ubuntu: "libmbedtls14" }
  - { retronas: "libmbedtls-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libmptcpwrap0", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libmysqlclient-dev", debian12: "libmysqlclient-dev", debian13: "default-libmysqlient-dev", fedora41: "", ubuntu: "libmysqlclient-dev" }
  - { retronas: "libneon27", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libnetfilter-queue-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libnetfilter-queue1", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libnfs-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libnode", debian12: "libnode108", debian13: "libnode115", fedora41: "", ubuntu: "" }
  - { retronas: "libpam-modules", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libpam0g", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libpam0g-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libpcap-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libpcap0.8dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libpcre2-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libprotobuf-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libreadline-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libsmbclient-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libspdlog-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libssh-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libssl-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libtdb-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libtirpc-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libtirpc3", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libtool", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libtool-bin", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libtracker-miner", debian12: "", debian13: "", fedora41: "", ubuntu: "libtracker-miner-2.0-dev" }
  - { retronas: "libtracker-sparql", debian12: "libtracker-sparql-2.0-dev", debian13: "libtracker-sparql-3.0-dev", fedora41: "", ubuntu: "libtracker-sparql-2,0-dev" }
  - { retronas: "libuchardet-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libwrap0", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "libxerces-c-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "lm-sensors", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "lrzsz", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "lynx", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "m4", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "make", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "man2html", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "mc", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "meson", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "meson", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "minicom", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "mtr", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "nbd-client", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "netatalk", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "netbase", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "nfs-common", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "nfs-common", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "nfs-kernel-server", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "nftables", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "nginx", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "nginx-light", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "ninja-build", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "nmap", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "npm", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "ntfs-3g", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "openntpd", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "openssh-client", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "openssh-server", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "openssh-sftp-server", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "openssl", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "p7zip-full", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "p7zip-rar", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "pandoc", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "perl", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "po4a", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "ppp", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "proftpd-core", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "protobuf-compiler", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "pwgen", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "python-is-python3", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "python3", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "python3-boto3", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "python3-bs4", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "python3-firewall", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "python3-html5lib", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "python3-pip", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "python3-setuptools", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "python3-venv", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "python3-wheel", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "rsyslog", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "samba", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "samba-vfs-modules", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "scons", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "screen", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "smartmontools", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "socat", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "sshfs", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "strace", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "sudo", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "syncthing", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "systemtap-sdt-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "tcpd", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "tcpdump", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "telnet", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "telnetd", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "tftpd-hpa", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "traceroute", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "tracker", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "udisks2", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "udisks2-btrfs", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "udisks2-lvm2", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "unrar", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "unzip", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "util-linux", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "wget", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "wvdail", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "x11vnc", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "xfsprogs", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "xinetd", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "xlinkkai", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "xvfb", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  - { retronas: "zlib1g-dev", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
  #  - { retronas: "", debian12: "", debian13: "", fedora41: "", ubuntu: "" }
