- hosts: localhost

  vars:
    - my_name: "RetroNAS dependencies"
    - my_file: "retronas_dependencies"

    - packages:
      - jq
      - sudo
      - git 
      - dialog 
      - jq

    - directories:
      - bin
      - etc
      - scripts
      - log


  tasks:

  - name: "{{ my_name }} - Load RetroNAS config"
    include_vars: retronas_vars.yml

  - name: "{{ my_name }} - configure program directories"
    file:
      path: "{{ retronas_root }}/{{ item }}"
      owner: root
      group: root
      mode: 0755
      state: directory
    with_items: "{{ directories }}"

  - name: "{{ my_name }} - required packages"
    apt:
      name: "{{ item }}"
      state: latest
    with_items: "{{ packages }}"

  - name: "{{ my_name }} - configure top level share directory"
    file:
      path: "{{ retronas_path }}"
      owner: "{{ retronas_user }}"
      group: "{{ retronas_user }}"
      mode: 0775
      state: directory
