---
- hosts: localhost
  become: true

  vars:
    my_name: "RetroNAS dependencies"
    my_file: "retronas_dependencies"

    packages:
      - jq
      - sudo
      - git
      - dialog

    directories:
      - bin
      - etc
      - scripts
      - log
      - cache

  tasks:

    - name: "{{ my_name }} - Load RetroNAS config"
      ansible.builtin.include_vars: retronas_vars.yml

    - name: "{{ my_name }} - configure root dir"
      ansible.builtin.file:
        path: "{{ retronas_root }}"
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: "{{ my_name }} - configure program directories"
      ansible.builtin.file:
        path: "{{ retronas_root }}/{{ item }}"
        owner: root
        group: root
        mode: 2755
        state: directory
      loop: "{{ directories }}"

    - name: "{{ my_name }} - configure top level share directory"
      ansible.builtin.file:
        path: "{{ retronas_path }}"
        owner: "{{ retronas_user }}"
        group: "{{ retronas_user }}"
        mode: 2775
        state: directory

    - ansible.builtin.include_role:
        name: "{{ role }}"
      loop:
        - retronas.role.package.latest
        - retronas.role.cache
      loop_control:
        loop_var: role
