#
# FIREWALL
#
- name: "{{ my_name }} - checking firewall rule"
  ansible.builtin.stat:
    path: /etc/firewalld/services
  register: firewalld_services

- name: "{{ my_name }} - enable firewall rule"
  ansible.posix.firewalld:
    zone: "{{ item.zone | default('retro') }}"
    port: "{{ item.port }}/{{ item.protocol }}"
    permanent: "{{ item.permanent | default('true') }}"
    state: "{{ item.state | default('enabled') }}"
    immediate: true
  loop: "{{ firewalld.ports }}"
  when: firewalld.ports is defined and
        firewalld_services.stat.exists