---
- name: "{{ my_name }} - Load RetroNAS config"
  ansible.builtin.include_vars: retronas_vars.yml

- name: "{{ my_name }} - Install from backports repo"
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
    default_release: "{{ ansible_distribution_release }}-backports"
  notify: "{{ my_name }} - Restart service"
  when: (ansible_distribution == 'Debian' and ansible_distribution_major_version | int < 13) or
        ansible_distribution == 'Ubuntu'

- name: "{{ my_name }} - Install from repo"
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
  notify: "{{ my_name }} - Restart service"
  when: ansible_distribution == 'Debian' and
        ansible_distribution_major_version | int >= 13

- name: "{{ my_name }} - enable startup services"
  ansible.builtin.service:
    name: "{{ my_service }}"
    state: started
    enabled: true
    daemon_reload: true

- ansible.builtin.import_role:
    name: retronas.role.firewalld.port
